name: Deploy HTML ke GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout kode
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Configure Pages site otomatis
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5

      # 3️⃣ Deploy HTML ke GitHub Pages
      - name: Deploy ke GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          commit_message: "Deploy update halaman HTML dari workflow"
